services:
  ollama:
    build: .
    container_name: ollama-server
    volumes:
      - ./ollama_models:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama serve"]

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-report-service
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434