services:
  ollama:
    build: .
    container_name: ollama-server
    volumes:
      - ./ollama_models:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama serve"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-report-service
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy 
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434